routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Area
    Route::delete('areas/destroy', 'AreaController@massDestroy')->name('areas.massDestroy');
    Route::resource('areas', 'AreaController');

    // Place
    Route::delete('places/destroy', 'PlaceController@massDestroy')->name('places.massDestroy');
    Route::resource('places', 'PlaceController');

    // Plant
    Route::delete('plants/destroy', 'PlantController@massDestroy')->name('plants.massDestroy');
    Route::resource('plants', 'PlantController', ['except' => ['edit', 'update']]);

    // Image
    Route::delete('images/destroy', 'ImageController@massDestroy')->name('images.massDestroy');
    Route::post('images/media', 'ImageController@storeMedia')->name('images.storeMedia');
    Route::post('images/ckmedia', 'ImageController@storeCKEditorImages')->name('images.storeCKEditorImages');
    Route::resource('images', 'ImageController');

    // Phenologiaca Observation
    Route::delete('phenologiaca-observations/destroy', 'PhenologiacaObservationController@massDestroy')->name('phenologiaca-observations.massDestroy');
    Route::resource('phenologiaca-observations', 'PhenologiacaObservationController');

    // Event Genre
    Route::delete('event-genres/destroy', 'EventGenreController@massDestroy')->name('event-genres.massDestroy');
    Route::resource('event-genres', 'EventGenreController');

    // User Type
    Route::delete('user-types/destroy', 'UserTypeController@massDestroy')->name('user-types.massDestroy');
    Route::resource('user-types', 'UserTypeController');

    // Contacts
    Route::delete('contacts/destroy', 'ContactsController@massDestroy')->name('contacts.massDestroy');
    Route::resource('contacts', 'ContactsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});
Route::get('galleria', 'GalleriaController@index');
Route::get('home', 'HomePageController@index');
Route::get('ricerca', 'RicercaController@index');
//Route::get('formulario', 'FormularioController@index');
Route::view('formulario', 'formulario');
Route::post('submit', 'FormularioController@salva');
Route::view('amministrazione', 'amministrazione');
Route::post('submit', 'AmministrazioneController@saveDataPlants');
Route::view('registrazione', 'registrazione');
Route::post('submit', 'RichiestaDatiController@login');
//Route::view('home', 'home');
//Route::post('home', 'AdminControllerController@registrati');

app/Models/EventGenre.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class EventGenre extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'event_genres';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'event_name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/EventGenreController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyEventGenreRequest;
use App\Http\Requests\StoreEventGenreRequest;
use App\Http\Requests\UpdateEventGenreRequest;
use App\Models\EventGenre;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class EventGenreController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('event_genre_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $eventGenres = EventGenre::all();

        return view('admin.eventGenres.index', compact('eventGenres'));
    }

    public function create()
    {
        abort_if(Gate::denies('event_genre_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.eventGenres.create');
    }

    public function store(StoreEventGenreRequest $request)
    {
        $eventGenre = EventGenre::create($request->all());

        return redirect()->route('admin.event-genres.index');
    }

    public function edit(EventGenre $eventGenre)
    {
        abort_if(Gate::denies('event_genre_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.eventGenres.edit', compact('eventGenre'));
    }

    public function update(UpdateEventGenreRequest $request, EventGenre $eventGenre)
    {
        $eventGenre->update($request->all());

        return redirect()->route('admin.event-genres.index');
    }

    public function show(EventGenre $eventGenre)
    {
        abort_if(Gate::denies('event_genre_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.eventGenres.show', compact('eventGenre'));
    }

    public function destroy(EventGenre $eventGenre)
    {
        abort_if(Gate::denies('event_genre_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $eventGenre->delete();

        return back();
    }

    public function massDestroy(MassDestroyEventGenreRequest $request)
    {
        EventGenre::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/eventGenres/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.eventGenre.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.event-genres.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="event_name">{{ trans('cruds.eventGenre.fields.event_name') }}</label>
                <input class="form-control {{ $errors->has('event_name') ? 'is-invalid' : '' }}" type="text" name="event_name" id="event_name" value="{{ old('event_name', '') }}">
                @if($errors->has('event_name'))
                    <span class="text-danger">{{ $errors->first('event_name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.eventGenre.fields.event_name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/eventGenres/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.eventGenre.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.event-genres.update", [$eventGenre->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="event_name">{{ trans('cruds.eventGenre.fields.event_name') }}</label>
                <input class="form-control {{ $errors->has('event_name') ? 'is-invalid' : '' }}" type="text" name="event_name" id="event_name" value="{{ old('event_name', $eventGenre->event_name) }}">
                @if($errors->has('event_name'))
                    <span class="text-danger">{{ $errors->first('event_name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.eventGenre.fields.event_name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/eventGenres/index.blade.php
@extends('layouts.admin')
@section('content')
@can('event_genre_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.event-genres.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.eventGenre.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.eventGenre.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-EventGenre">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.eventGenre.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.eventGenre.fields.event_name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($eventGenres as $key => $eventGenre)
                        <tr data-entry-id="{{ $eventGenre->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $eventGenre->id ?? '' }}
                            </td>
                            <td>
                                {{ $eventGenre->event_name ?? '' }}
                            </td>
                            <td>
                                @can('event_genre_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.event-genres.show', $eventGenre->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('event_genre_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.event-genres.edit', $eventGenre->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('event_genre_delete')
                                    <form action="{{ route('admin.event-genres.destroy', $eventGenre->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('event_genre_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.event-genres.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-EventGenre:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/eventGenres/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.eventGenre.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.event-genres.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.eventGenre.fields.id') }}
                        </th>
                        <td>
                            {{ $eventGenre->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.eventGenre.fields.event_name') }}
                        </th>
                        <td>
                            {{ $eventGenre->event_name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.event-genres.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection